use_frameworks!

target 'PhotoViewController_Example' do
  pod 'PhotoViewController', :path => '../'

  target 'PhotoViewController_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
